### ISSUE TITLE
Evaluate fixated locations Script Failed!

### ISSUE THREAD

**Issue by AtlasGo** [ischtz/gridfix#2] opened 2022-02-09 13:57 UTC
Dear gridfix developers,

I have met a problem when I ran the demo script from your tutorial.

> \# Determine fixated and non-fixated grid cells
> fix_on_image = grid.fixated(subj_fix)
> print(fix_on_image)
> 
> \# Number of returned values - this should match number of grid cells
> print(len(fix_on_image))

The output showed the error as follow:

> KeyError                                  Traceback (most recent call last)
> [/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py](https://localhost:8080/#) in get_loc(self, key, method, tolerance)
>    3360             try:
> -> 3361                 return self._engine.get_loc(casted_key)
>    3362             except KeyError as err:
> 
> 5 frames
> pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
> 
> pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()
> 
> KeyError: None
> 
> The above exception was the direct cause of the following exception:
> 
> KeyError                                  Traceback (most recent call last)
> [/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py](https://localhost:8080/#) in get_loc(self, key, method, tolerance)
>    3361                 return self._engine.get_loc(casted_key)
>    3362             except KeyError as err:
> -> 3363                 raise KeyError(key) from err
>    3364 
>    3365         if is_scalar(key) and isna(key) and not self.hasnans:
> 
> KeyError: None

Please help me fix it.

Best regards,
Jian Li

**Comment by ischtz** [comment] 2022-02-09 15:30
Hi Jian Li, 

thanks for reporting this! I haven't run the tutorial script in a while but can reproduce the error (Python 3.8, pandas 1.1.3). 

It looks like this is due to changes in how pandas handles indexing since the last time I used this toolbox in a project. I will need to go over the code and check for all places where it needs to be updated. I hope to take a look over the next few days and get back to you!

**Comment by AtlasGo** [comment] 2022-02-10 09:34
Great. Thank you, ischtz.

**Comment by ischtz** [comment] 2022-02-10 20:25
This should be fixed now (was not related to pandas at all, but to newer functionality of gridfix to analyze fixation times and durations). Could you please try installing the current version manually (download zip or clone, "python setup.py install") and check if this fixes the above error for you? Thanks!

Note: While debugging, I found and corrected another bug in the first tutorial (one cell below, related to changes in arguments to the .fixated() method). Please refer to https://github.com/ischtz/gridfix-tutorial/blob/master/Tutorial1_ImagesRegionsFixations.ipynb for now to see the corrected version. I will update the tutorial package shortly.

**Comment by ischtz** [comment] 2022-02-27 21:33
I uploaded a new package version to PyPI that fixes the issue with the updated tutorial files, so I'm closing this issue - feel free to comment in case you still see errors after updating. Thanks again for reporting!

**Closed as completed by ischtz** 2022-02-27 21:33 UTC
